services:
  api:
    build:
      context: .
      target: ${BUILD_MODE:-dev}
    container_name: trip-api
    ports:
      - "8081:8081"
    networks:
      - splitngo-net
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    command: >
      sh -c "
      if [ '${BUILD_MODE}' = 'prod' ]; then
        java -jar app.jar
      else
        ./mvnw spring-boot:run
      fi"

  db:
    image: mysql:8
    container_name: splitngo-db
    ports:
      - "3306:3306"
    networks:
      - splitngo-net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:


networks:
  splitngo-net:
    external: true